version: '3.8'

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:alpine3.17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: company
      POSTGRES_USER: company
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
